# Generated by Django 2.0.7 on 2018-07-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.IntegerField()),
                ('file_id', models.IntegerField()),
                ('pre_process', models.BooleanField(default=False)),
                ('solution_process', models.BooleanField(default=False)),
                ('post_process', models.BooleanField(default=False)),
                ('fatigue_process', models.BooleanField(default=False)),
                ('fracture_process', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
            ],
        ),
    ]
