# Generated by Django 2.0.7 on 2018-07-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Songs',
        ),
        migrations.AddField(
            model_name='job',
            name='all',
            field=models.BooleanField(default=False),
        ),
    ]
