# Generated by Django 2.0.7 on 2018-07-17 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0002_auto_20180717_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('id',)},
        ),
    ]
