# Generated by Django 2.0.7 on 2018-07-18 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0003_auto_20180717_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='all',
            new_name='run_all',
        ),
    ]
